version: "3.7"
name: sample-microservices
services:

  config-service:
    ports:
      - "8080"
    environment:
      spring.profiles.active: docker, native
    image: ttechlab/config-service:1.0-SNAPSHOT
    volumes:
      - ./config:/var/lib/config-repo
    healthcheck:
      test: curl --fail http://config-service:8080/actuator/info || exit 1
      interval: 10s
      start_period: 10s
      timeout: 3s
      retries: 3
    depends_on:
      discovery-service:
        condition: service_healthy

  discovery-service:
    environment:
      spring.profiles.active: docker
    image: ttechlab/discovery-service:1.0-SNAPSHOT
    ports:
      - "8061:8080"
    healthcheck:
      test: curl --fail http://discovery-service:8080/eureka/v2/apps || exit 1
      interval: 10s
      start_period: 10s
      timeout: 3s
      retries: 3

  gateway-service:
    environment:
      spring.profiles.active: docker
    image: ttechlab/gateway-service:1.0-SNAPSHOT
    ports:
      - "8060:8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service

  department-service:
    environment:
      spring.profiles.active: docker
    image: ttechlab/department-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - gateway-service

  employee-service:
    environment:
      spring.profiles.active: docker
    image: ttechlab/employee-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - gateway-service
  
  organization-service:
    environment:
      spring.profiles.active: docker
    image: ttechlab/organization-service:1.0-SNAPSHOT
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - gateway-service
  