services:
    db:
      container_name: mysql_db
      image: mysql
      ports:
       - "3306:3306"  
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: example


      volumes:
         - ./data:/var/lib/mysql
         - ./init:/docker-entrypoint-initdb.d/:ro