server:
  port: 8080

spring:
  application:
    name: config-server

  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: file:///var/lib/config-repo/

  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/

management:
  tracing:
    sampling:
      probability: 1.0