server:
  port: 0

spring:
  application:
    name: config-service
  profiles:
    active: native

  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: file:///C:/visual studio projects/java/sample-spring-microservice/config/

  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  tracing:
    sampling:
      probability: 1.0